version: '3.8'

services:
  mongodb-crud-api:
    build: .
    image: efexzium/mongodb-fast-api:latest
    ports:
      - "8002:8002"
    environment:
      - MONGO_URI=mongodb+srv://Focus1:PjHN8M4P7bR1tuKS@cluster0.tvssqty.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - DB_NAME=mystore
      - COLLECTION=items
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s